
-- Database: bioskopku_db
CREATE DATABASE IF NOT EXISTS `bioskopku_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bioskopku_db`;

-- Table: users
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(64) NULL,
  `iterations` INT NOT NULL DEFAULT 10000,
  `genres` TEXT NULL,
  `avatar` VARCHAR(255) NULL,
  `role` VARCHAR(50) DEFAULT 'VIP Member',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
